name: Actions Test
on:
  push:
    paths:
      - 'pathFile.txt'
jobs: 
  Make-Database:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: echo "The job was automatically triggered bc pathfile changed."
      - run: echo $"$PWD"/"make_json.py"
      - run: python $"$PWD"/"make_json.py"
      - run: echo "Changed demos/db.json to contain the updated json database."
